---
title: "EVMP covariate analysis"
author: ""
date: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(knitr)
# opts_knit$set(root.dir=normalizePath('../')) # this is required if Rmd is nested below the project directory
opts_chunk$set(fig.path = "../output/figures/") # corrected path and added dev. Needed to specify a subdirectory for figs
```

```{r, echo=FALSE}
# library(here)
# here()
# install.packages("bindrcpp")

knitr::opts_knit$set(root.dir=normalizePath('../')) # this is required if Rmd is nested below the project directory


suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(fs))
suppressPackageStartupMessages(library(sf))
# library(raster)
suppressPackageStartupMessages(library(janitor))
suppressPackageStartupMessages(library(readxl))
# library(glue)
suppressPackageStartupMessages(library(mapview))
# library(ggmap)
# library(ggrepel)
suppressPackageStartupMessages(library(viridis))
# library(ggExtra)
suppressPackageStartupMessages(library(ggstance))
suppressPackageStartupMessages(library(readxl))
suppressPackageStartupMessages(library(DT))
# library(kableExtra)
suppressPackageStartupMessages(library(lubridate))
suppressPackageStartupMessages(library(skimr)) 
suppressPackageStartupMessages(library(dataMaid))
# library(ggmap)
library(lubridate)
library(mapview)
library(visdat)
library(gt)
```


## Climate

### Bear Lake Snotel
```{r}
# data\covariates\climate\BearToothSnotel
snotel <- read_csv("./data/covariates/climate/BearLakeSnotel/snotel_2read.csv") %>% 
  janitor::clean_names()
```

```{r}
snotel <- snotel %>% 
  rename(swe = snow_water_equivalent_in_start_of_day_values) %>% 
  rename(ppt_accum_in = precipitation_accumulation_in_start_of_day_values) %>% 
  rename(temp_max_f = air_temperature_maximum_deg_f) %>%
  rename(temp_min_f = air_temperature_minimum_deg_f) %>%
  rename(temp_avg_f = air_temperature_average_deg_f) %>%
  rename(ppt_incr_in = precipitation_increment_in) 

snotel <- snotel %>%
  mutate(date = mdy(date)) %>% 
  mutate(month = month(date,label = TRUE),
         doy = yday(date),
         year = year(date))

```

```{r}

snotel <- snotel %>% 
  mutate(ppt_accum_mm = 25.4*ppt_accum_in) %>% 
  mutate(ppt_incr_mm = 25.4*ppt_incr_in)

snotel %>%
  visdat::vis_dat()
```

What day had the latest peak swe?


```{r}
top_ppt_accum <- snotel %>% 
  group_by(year) %>% 
  summarise(ppt_accum_mm_max = max(ppt_accum_mm)) %>% 
  ungroup()

ppt.pl <- top_ppt_accum %>% 
  filter(year >1980 & year < 2019) %>% 
  # mutate(year = as.character(year)) %>%
  ggplot(aes(year,ppt_accum_mm_max)) +
  geom_col(fill = "ivory4") +
  labs(x="", y = "Accumulated precipitation (mm)", caption = "Bear Lake Snotel Data") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_continuous(breaks = seq(from = 1980, to = 2018, by = 5))
  
# ppt.pl

```

```{r}
top_swe <- snotel %>% 
  mutate(year = as.character(year)) %>%
  group_by(year) %>% 
  summarise(max_swe = max(swe)) %>% 
  ungroup()


swe.pl <- top_swe %>%
  filter(year>1980 & year <2019) %>% 
  # mutate(year = as.character(year)) %>%
  mutate(year = as.integer(year)) %>%
  ggplot(aes(year,max_swe)) +
  geom_col(fill = "ivory4") +
  # geom_jitter() +
  labs(x="", y = "SWE") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_continuous(breaks = seq(from = 1980, to = 2018, by = 5))

# swe.pl

# ggsave("./output/figures_exported/bearLk_SWE.png", width = 3.85, height = 3.85)

```

```{r}
cowplot::plot_grid(swe.pl,ppt.pl, labels = "AUTO")
# ggsave("./output/figures_exported/bear_lk_swe_ppt.png", width = 6.5, height = 3.8)
```


```{r}
top_swe %>% 
  select(year, max_swe) %>% 
  datatable(rownames = FALSE, filter = "top")
```

## Physiographic
```{r}
# distince from stream



```

## Elk
```{r}

elk.raw <- read_csv("./data/covariates/elk/RMNP_Population_summary.csv") %>% 
  janitor::clean_names()

```

```{r}
elk.raw <- elk.raw %>% 
  mutate(year = as.integer(year))

## write to disk
# write_csv(elk.raw, "./data/covariates/elk/RMNP_elk_pop_summary_cln.csv")

elk.raw %>% 
  ggplot(aes(x = year, y = median)) +
  geom_point(color = "blue") +
  geom_line(color = "blue") +
  geom_line(aes(y = p025), color = "red", lty = "dashed") +
  geom_line(aes(y = p975), color = "red", lty = "dashed") +
  theme_minimal() +
  labs(x = "Year", y = "Median elk populatiop estimate", caption = "Modeled elk pop: RMNP_Population_summary.csv ")

# ggsave("./output/figures_exported/elk_population.png", width = 5, height = 4, dpi = 300)
```

```{r}
elk.raw %>% 
  gt::gt() %>% 
  gt::gtsave("./output/tables/elkpop.rtf")

elk.raw %>% 
  summarytools::descr(median) 

elk.raw %>% 
  arrange(desc(median))

elk.raw %>% 
  arrange((median))
```


## Moose

## NDVI Time Series

```{r}



```

